version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    build: ../src/ui
    image: "${USERNAME}/ui:${TAG2}"
    ports:
      - "${PORT_UI}:${PORT_UI}/tcp"
    networks:
      - front_net
  post:
    build: ../src/post-py
    image: "${USERNAME}/post:${TAG1}"
    networks:
      - back_net
      - front_net
  comment:
    build: ../src/comment
    image: "${USERNAME}/comment:${TAG1}"
    networks:
      - back_net
      - front_net
  prometheus:
    image: andrey874/prometheus
    ports: 
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes: 
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'    

volumes:
  prometheus_data:
  post_db:

networks:
  back_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.0/24
  front_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
  monit_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.3.0/24
        

